version: "3"
services:
  app:
    container_name: cloudamqp-message-creator
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '${PORT}:${PORT}'